sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 24104401
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tJSbaVsGdaqDrJGBR8c
    access-key-secret: o18VdJqdqliAaYAtOBOJ9mbDx3srRk
    bucket-name:  java-aiil
